### PR TITLE
Addition of Spanish Localization for "using AWB"

### PR DESCRIPTION
**Pull request by AlvaroMolinaCL**
Addition of Spanish Localization for "using AWB". Thanks.

### CODE REVIEW

**Comment by reedy** [comment]
Done

**Comment by AlvaroMolinaCL** [comment]
@reedy: You forgot to merge the commit.

**Comment by reedy** [comment]
No, I didn't. We don't work in git. So https://github.com/reedy/AutoWikiBrowser/commit/184fb22904b9ebd043817e44e3d2f92742d7872c

**Comment by AlvaroMolinaCL** [comment]
Okay. Thanks for the Clarification.

**Pull request closed without merging**
