### PR TITLE
Change (JSON)Pages with a page property to Pages with a page property…

### PR DESCRIPTION
**Pull request by Kumioko**
… (JSON)

Change (JSON)Pages with a page property to Pages with a page property (JSON) so it sorts properly

### CODE REVIEW

**Comment by reedy** [comment]
It's mostly done on purpose for debugging reasons (to force it to the top, I think)

**Comment by Kumioko** [comment]
Oh ok. No problem

**Comment by reedy** [comment]
At some point, all the providers should be using json... :)

**Comment by Kumioko** [comment]
You would think so. I'm going to go ahead and close this request.

**Pull request closed without merging**
